import type {
  OnboardingPatient,
  OnboardingKPI,
} from "@/types/onboarding";

export const onboardingKPIs: OnboardingKPI[] = [
  { label: "Referral Validation", value: "12", color: "warning", delta: "0%" },
  { label: "Case History Collection", value: "8", color: "primary", delta: "0%" },
  { label: "VOB Pending", value: "15", color: "accent", delta: "0%" },
  { label: "PA Pending", value: "6", color: "secondary", delta: "0%" },
  { label: "Ready to Schedule", value: "9", color: "success", delta: "0%" },
  { label: "Total In Pipeline", value: "50", color: "primary", delta: "0%" },
];

export const onboardingPatients: OnboardingPatient[] = [
  {
    id: "1",
    name: "Emma Rodriguez",
    triagePriority: "Tier 1 Urgent",
    primaryConcern: "Expressive Language Delay",
    referralDate: "11/15/2024",
    dateOfBirth: "03/12/2021",
    caregiverGuardian: "Maria Rodriguez",
    insurancePayer: "Medicaid",
    referralSource: "Pediatrician",
    steps: {
      referralValidation: "Complete",
      slpCaseHistory: "In Progress",
      vobSlpBenefits: "Not Started",
      paSlpEvalCodes: "Not Started",
      schedulingStatus: "Not Started",
    },
    assignedSLP: "Dr. Sarah Mitchell, CCC-SLP",
    daysInOnboarding: 12,
  },
  {
    id: "2",
    name: "Jackson Park",
    triagePriority: "Tier 2 Priority",
    primaryConcern: "Articulation Disorder",
    referralDate: "11/18/2024",
    dateOfBirth: "08/22/2018",
    caregiverGuardian: "Jennifer Park",
    insurancePayer: "Blue Cross Blue Shield",
    referralSource: "School District",
    steps: {
      referralValidation: "Complete",
      slpCaseHistory: "Complete",
      vobSlpBenefits: "Complete",
      paSlpEvalCodes: "Pending",
      schedulingStatus: "Not Started",
    },
    assignedSLP: "James Rivera, CCC-SLP",
    daysInOnboarding: 9,
  },
  {
    id: "3",
    name: "Sophia Chen",
    triagePriority: "Tier 3 Routine",
    primaryConcern: "Fluency/Stuttering",
    referralDate: "11/20/2024",
    dateOfBirth: "01/15/2015",
    caregiverGuardian: "David Chen",
    insurancePayer: "Aetna",
    referralSource: "Private Practice",
    steps: {
      referralValidation: "Complete",
      slpCaseHistory: "Complete",
      vobSlpBenefits: "Complete",
      paSlpEvalCodes: "Complete",
      schedulingStatus: "Ready to Schedule",
    },
    assignedSLP: "Emily Chen, CCC-SLP",
    daysInOnboarding: 7,
  },
  {
    id: "4",
    name: "Marcus Johnson",
    triagePriority: "Tier 1 Urgent",
    primaryConcern: "Dysphagia/Feeding",
    referralDate: "11/22/2024",
    dateOfBirth: "09/03/2019",
    caregiverGuardian: "Angela Johnson",
    insurancePayer: "UnitedHealthcare",
    referralSource: "Hospital",
    steps: {
      referralValidation: "In Progress",
      slpCaseHistory: "Not Started",
      vobSlpBenefits: "Not Started",
      paSlpEvalCodes: "Not Started",
      schedulingStatus: "Not Started",
    },
    assignedSLP: "Dr. Sarah Mitchell, CCC-SLP",
    daysInOnboarding: 5,
  },
  {
    id: "5",
    name: "Lily Thompson",
    triagePriority: "Tier 2 Priority",
    primaryConcern: "Receptive Language",
    referralDate: "11/25/2024",
    dateOfBirth: "05/14/2020",
    caregiverGuardian: "Robert Thompson",
    insurancePayer: "Cigna",
    referralSource: "Early Intervention",
    steps: {
      referralValidation: "Complete",
      slpCaseHistory: "Pending",
      vobSlpBenefits: "Not Started",
      paSlpEvalCodes: "Not Started",
      schedulingStatus: "Not Started",
    },
    assignedSLP: "Michael Torres, CF-SLP",
    daysInOnboarding: 2,
  },
  {
    id: "6",
    name: "Aiden Williams",
    triagePriority: "Tier 3 Routine",
    primaryConcern: "Voice Disorder",
    referralDate: "11/28/2024",
    dateOfBirth: "11/07/2016",
    caregiverGuardian: "Sarah Williams",
    insurancePayer: "Tricare",
    referralSource: "ENT Specialist",
    steps: {
      referralValidation: "Not Started",
      slpCaseHistory: "Not Started",
      vobSlpBenefits: "Not Started",
      paSlpEvalCodes: "Not Started",
      schedulingStatus: "Not Started",
    },
    assignedSLP: "James Rivera, CCC-SLP",
    daysInOnboarding: 1,
  },
  {
    id: "7",
    name: "Mia Garcia",
    triagePriority: "Tier 2 Priority",
    primaryConcern: "AAC Needs",
    referralDate: "12/01/2024",
    dateOfBirth: "04/08/2017",
    caregiverGuardian: "Carlos Garcia",
    insurancePayer: "Medicare",
    referralSource: "Neurologist",
    steps: {
      referralValidation: "Complete",
      slpCaseHistory: "Complete",
      vobSlpBenefits: "In Progress",
      paSlpEvalCodes: "Not Started",
      schedulingStatus: "Not Started",
    },
    assignedSLP: "Emily Chen, CCC-SLP",
    daysInOnboarding: 1,
  },
  {
    id: "8",
    name: "Noah Martinez",
    triagePriority: "Tier 1 Urgent",
    primaryConcern: "Apraxia of Speech",
    referralDate: "12/03/2024",
    dateOfBirth: "02/18/2022",
    caregiverGuardian: "Isabella Martinez",
    insurancePayer: "Self-Pay",
    referralSource: "Parent Self-Referral",
    steps: {
      referralValidation: "Issue",
      slpCaseHistory: "Not Started",
      vobSlpBenefits: "Not Started",
      paSlpEvalCodes: "Not Started",
      schedulingStatus: "Not Started",
    },
    assignedSLP: "Michael Torres, CF-SLP",
    daysInOnboarding: 1,
  },
];

export async function fetchOnboardingPatients(): Promise<OnboardingPatient[]> {
  return onboardingPatients;
}

export async function fetchOnboardingKPIs(): Promise<OnboardingKPI[]> {
  return onboardingKPIs;
}
