import type { PatientChartData } from "@/types/patient-chart"

const MOCK_PATIENT_CHART: PatientChartData = {
  patient: {
    id: "pt-001",
    name: "Emma Stevens",
    dateOfBirth: "03/15/2019",
    age: 5,
    gender: "Female",
    medicalRecordNumber: "PT-2024-0847",
    patientSince: "01/15/2024",
    status: "Active",
    avatar: "",
    providerId: "prov-001",
    referringPhysicianId: "prov-002",
  },
  provider: {
    id: "prov-001",
    name: "Dr. Sarah Martinez, CCC-SLP",
    credentials: "CCC-SLP",
    specialty: "Speech-Language Pathology",
  },
  referringPhysician: {
    id: "prov-002",
    name: "Dr. Michael Chen, MD",
    credentials: "MD",
    specialty: "Pediatrics",
  },
  diagnoses: [
    {
      id: "dx-001",
      patientId: "pt-001",
      code: "F80.2",
      description: "Mixed receptive-expressive language disorder",
      onsetDate: "01/15/2024",
      type: "Primary",
    },
    {
      id: "dx-002",
      patientId: "pt-001",
      code: "F80.0",
      description: "Phonological disorder",
      onsetDate: "01/15/2024",
      type: "Secondary",
    },
  ],
  assessments: [
    {
      id: "assess-001",
      patientId: "pt-001",
      name: "CELF-5",
      standardScore: 72,
      percentile: 3,
      date: "01/15/2024",
    },
    {
      id: "assess-002",
      patientId: "pt-001",
      name: "GFTA-3",
      standardScore: 68,
      percentile: 2,
      date: "01/15/2024",
    },
    {
      id: "assess-003",
      patientId: "pt-001",
      name: "PLS-5",
      standardScore: 75,
      percentile: 5,
      date: "01/15/2024",
    },
  ],
  treatmentPlan: {
    id: "tp-001",
    patientId: "pt-001",
    certificationDate: "01/15/2024",
    recertDate: "07/15/2024",
    goals: [
      { id: "g-001", name: "Expressive Language", status: "In Progress" },
      { id: "g-002", name: "Receptive Language", status: "In Progress" },
      { id: "g-003", name: "Articulation", status: "In Progress" },
    ],
  },
  sessions: [
    {
      id: "sess-001",
      patientId: "pt-001",
      date: "03/15/2024",
      type: "Individual Therapy",
      cptCode: "92507",
      providerId: "prov-001",
      providerName: "Dr. Sarah Martinez, CCC-SLP",
      duration: "45 min",
      noteStatus: "Signed",
    },
    {
      id: "sess-002",
      patientId: "pt-001",
      date: "03/12/2024",
      type: "Individual Therapy",
      cptCode: "92507",
      providerId: "prov-001",
      providerName: "Dr. Sarah Martinez, CCC-SLP",
      duration: "45 min",
      noteStatus: "Signed",
    },
    {
      id: "sess-003",
      patientId: "pt-001",
      date: "03/08/2024",
      type: "Individual Therapy",
      cptCode: "92507",
      providerId: "prov-001",
      providerName: "Dr. Sarah Martinez, CCC-SLP",
      duration: "45 min",
      noteStatus: "Pending Co-signature",
    },
    {
      id: "sess-004",
      patientId: "pt-001",
      date: "03/05/2024",
      type: "Evaluation",
      cptCode: "92521",
      providerId: "prov-001",
      providerName: "Dr. Sarah Martinez, CCC-SLP",
      duration: "60 min",
      noteStatus: "Signed",
    },
    {
      id: "sess-005",
      patientId: "pt-001",
      date: "01/15/2024",
      type: "Initial Evaluation",
      cptCode: "92521",
      providerId: "prov-001",
      providerName: "Dr. Sarah Martinez, CCC-SLP",
      duration: "90 min",
      noteStatus: "Signed",
    },
  ],
  authorization: {
    id: "auth-001",
    patientId: "pt-001",
    authNumber: "AUTH-2024-0156",
    authorizedUnits: 24,
    usedUnits: 6,
    expirationDate: "07/15/2024",
    status: "Active",
    kxModifierStatus: "Threshold Not Met",
  },
  caregivers: [
    {
      id: "cg-001",
      patientId: "pt-001",
      name: "Jennifer Stevens",
      relationship: "Mother",
      phone: "(555) 123-4567",
      email: "jennifer.stevens@email.com",
      type: "Primary",
    },
    {
      id: "cg-002",
      patientId: "pt-001",
      name: "David Stevens",
      relationship: "Father",
      phone: "(555) 987-6543",
      email: "david.stevens@email.com",
      type: "Secondary",
    },
  ],
  homePrograms: [
    {
      id: "hp-001",
      patientId: "pt-001",
      name: "Articulation Practice Kit",
      assignedDate: "02/01/2024",
      frequency: "2x daily, 15 min",
      compliance: "Good Compliance",
      status: "Active",
    },
    {
      id: "hp-002",
      patientId: "pt-001",
      name: "Language Building Activities",
      assignedDate: "02/15/2024",
      frequency: "Daily, 20 min",
      compliance: "Fair Compliance",
      status: "Active",
    },
  ],
  documents: [
    {
      id: "doc-001",
      patientId: "pt-001",
      name: "Initial Evaluation Report",
      type: "evaluation",
      uploadDate: "01/15/2024",
    },
    {
      id: "doc-002",
      patientId: "pt-001",
      name: "Physician Referral Form",
      type: "referral",
      uploadDate: "01/10/2024",
    },
    {
      id: "doc-003",
      patientId: "pt-001",
      name: "Treatment Plan",
      type: "treatment_plan",
      uploadDate: "01/15/2024",
    },
    {
      id: "doc-004",
      patientId: "pt-001",
      name: "Progress Report - 30 Day",
      type: "progress_report",
      uploadDate: "02/15/2024",
    },
    {
      id: "doc-005",
      patientId: "pt-001",
      name: "Insurance Authorization",
      type: "authorization",
      uploadDate: "01/12/2024",
    },
  ],
  referralInfo: {
    referringProvider: "Dr. Michael Chen, MD - Pediatrics",
    referralDate: "01/10/2024",
    reasonForReferral: "Language delay, articulation concerns",
    status: "Active Treatment",
  },
}

export async function getPatientChart(
  _patientId: string
): Promise<PatientChartData> {
  return MOCK_PATIENT_CHART
}
