import type { Referral } from "@/types/referral"

const MOCK_REFERRALS: Referral[] = [
  {
    id: "REF-001",
    patient_name: "Emily Rodriguez",
    status: "documents_requested",
    triage_tier: "urgent",
    assigned_slp: "Sarah Johnson, CCC-SLP",
    referring_physician: "Dr. Maria Gonzalez",
    referral_source: "fax_ocr",
    primary_diagnosis_icd10: "F80.1 - Expressive Language Disorder",
    date_received: "2024-01-15",
    completeness_score: 6,
    completeness_total: 8,
    completeness_percentage: 75,
    insurance_payer: "Blue Cross Blue Shield",
  },
  {
    id: "REF-002",
    patient_name: "Michael Thompson",
    status: "ready_for_triage",
    triage_tier: "priority",
    assigned_slp: null,
    referring_physician: "Dr. Robert Kim",
    referral_source: "electronic",
    primary_diagnosis_icd10: "R47.02 - Dysarthria",
    date_received: "2024-01-14",
    completeness_score: 8,
    completeness_total: 8,
    completeness_percentage: 100,
    insurance_payer: "Medicare",
  },
  {
    id: "REF-003",
    patient_name: "Sophia Chen",
    status: "triaged",
    triage_tier: "routine",
    assigned_slp: "Michael Chen, CCC-SLP",
    referring_physician: "Dr. Jennifer Walsh",
    referral_source: "portal",
    primary_diagnosis_icd10: "F80.2 - Mixed Receptive-Expressive Language Disorder",
    date_received: "2024-01-13",
    completeness_score: 8,
    completeness_total: 8,
    completeness_percentage: 100,
    insurance_payer: "Aetna",
  },
  {
    id: "REF-004",
    patient_name: "Jacob Williams",
    status: "pending_review",
    triage_tier: "priority",
    assigned_slp: "Lisa Rodriguez, CF-SLP",
    referring_physician: "Dr. David Park",
    referral_source: "fax_ocr",
    primary_diagnosis_icd10: "F80.0 - Phonological Disorder",
    date_received: "2024-01-12",
    completeness_score: 5,
    completeness_total: 8,
    completeness_percentage: 63,
    insurance_payer: "United Healthcare",
  },
  {
    id: "REF-005",
    patient_name: "Isabella Davis",
    status: "scheduled",
    triage_tier: "urgent",
    assigned_slp: "Sarah Johnson, CCC-SLP",
    referring_physician: "Dr. Amanda Foster",
    referral_source: "phone",
    primary_diagnosis_icd10: "R13.10 - Dysphagia, Unspecified",
    date_received: "2024-01-11",
    completeness_score: 8,
    completeness_total: 8,
    completeness_percentage: 100,
    insurance_payer: "Medicaid",
  },
  {
    id: "REF-006",
    patient_name: "Ethan Martinez",
    status: "documents_requested",
    triage_tier: "routine",
    assigned_slp: null,
    referring_physician: "Dr. Lisa Chang",
    referral_source: "walk_in",
    primary_diagnosis_icd10: "F98.5 - Adult Onset Fluency Disorder",
    date_received: "2024-01-10",
    completeness_score: 4,
    completeness_total: 8,
    completeness_percentage: 50,
    insurance_payer: "Cigna",
  },
  {
    id: "REF-007",
    patient_name: "Olivia Johnson",
    status: "ready_for_triage",
    triage_tier: "priority",
    assigned_slp: "Michael Chen, CCC-SLP",
    referring_physician: "Dr. Thomas Brown",
    referral_source: "electronic",
    primary_diagnosis_icd10: "R49.0 - Dysphonia",
    date_received: "2024-01-09",
    completeness_score: 7,
    completeness_total: 8,
    completeness_percentage: 88,
    insurance_payer: "Humana",
  },
  {
    id: "REF-008",
    patient_name: "Noah Anderson",
    status: "pending_review",
    triage_tier: "routine",
    assigned_slp: null,
    referring_physician: "Dr. Sarah Wilson",
    referral_source: "fax_ocr",
    primary_diagnosis_icd10: "F80.4 - Speech and Language Development Delay",
    date_received: "2024-01-08",
    completeness_score: 3,
    completeness_total: 8,
    completeness_percentage: 38,
    insurance_payer: "Tricare",
  },
]

export async function getReferrals(): Promise<Referral[]> {
  return MOCK_REFERRALS
}
